feat: popup confirmation avant quit
SocialGouv/cdtn-admin pull request #1077
Opened 2023-10-11 08:34 UTC by Viczei

2023-10-11 08:35 UTC, Viczei commented on targets/frontend/src/components/contributions/answers/AnswerForm.tsx
> +  }, [isDirty]);
Cette partie affiche la popup lorsqu'on refresh ou ferme la page

2023-10-11 08:35 UTC, Viczei commented on targets/frontend/src/components/contributions/answers/AnswerForm.tsx
> +  };
Cette partie affiche la popup lorsqu'on part sur une autre page de l'admin

2023-10-11 13:34 UTC, maxgfr approved these changes
nice :)

2023-10-12 08:29 UTC, m-maillot approved these changes

2023-10-12 12:23 UTC, carolineBda requested changes
C'est pas bon on peut jamais quitter la page sans avoir la popup même après avoir sauvegarder

2023-10-19 10:01 UTC, carolineBda approved these changes
top

2023-10-19 10:03 UTC, merged