feat: ajout du champs hightlight a la table document
SocialGouv/cdtn-admin pull request #1118
Opened 2023-11-15 14:07 UTC by Viczei

2023-11-16 08:57 UTC, maxgfr requested changes

2023-11-16 08:57 UTC, maxgfr commented on targets/hasura/migrations/default/1698219011954_update_document_highlight/up.sql
> +where "source" = 'contributions'
```suggestion
where "source" = 'conventions_collectives'
```

Il me semble que c'est pas sur les contributions qu'on rajoute l'hightlight

De plus il faut vérifier qu'il y a pas déjà un highlight dans la convention collective

2023-11-29 08:36 UTC, maxgfr approved these changes

2023-11-29 08:36 UTC, m-maillot approved these changes

2023-11-29 09:18 UTC, merged