fix(ingester): handle legifrance new url style
SocialGouv/cdtn-admin pull request #334
Opened 2021-02-19 11:50 UTC by lionelB

- handle the new legifrance url
-  every link which does not belong to cdt or kali  is considered an external link ( we re-use the label from the service-public data )

2021-02-22 16:32 UTC, UnbearableBear approved these changes
Nice, mais je me demande si on ne devrait pas fallback sur une external url plutot que de retourner `[]` dans certains cas. Faudrait voir ce que ça implique côté front, on peut regarder une prochaine fois aussi, ce n’est pas le but de cette PR

2021-02-22 16:35 UTC, UnbearableBear commented on targets/ingester/src/transform/fichesServicePublic/parseReference.js
> +      return [];
ici par exemple, on n’arrive pas à extraire la ref et au lieu de la considérer comme external on la zappe non ?

2021-02-22 17:33 UTC, lionelB commented on targets/ingester/src/transform/fichesServicePublic/parseReference.js
> +      return [];
effectivement, je fais ca pour les ref sur des articles du code du travail qu'on ne retrouve pas. ca pourrait arriver pour des articles obsoletes. Peut etre qu'on peut les laisser en externalcela dit, le temps que ce soit mis a jour coté service-public

2021-02-23 14:33 UTC, m-maillot requested changes
Comments have broken the script :(

2021-02-23 14:55 UTC, lionelB commented on targets/ingester/src/cli.js
> +    // await updateVersion(pkgName, version);
:facepalm: 
 I'll fix it

2021-02-23 15:32 UTC, m-maillot approved these changes
👍

2021-02-23 16:08 UTC, merged