fix(frontend): references inaccessibles
SocialGouv/cdtn-admin pull request #696
Opened 2022-01-17 17:09 UTC by maxgfr

fix #649
fix #648

2022-01-18 09:43 UTC, m-maillot requested changes

2022-01-18 09:43 UTC, m-maillot commented on targets/frontend/src/pages/ghost-documents.tsx
> +              <Td>{parent.title}</Td>
De ce que je comprends, c'est le lien de la ficher que l'on veut supprimer, pas le lien du Parent (qui est le thème). Du coup, il faut supprimer le lien sur le `document.title` (cf ligne 79)

2022-01-18 10:30 UTC, maxgfr commented on targets/frontend/src/pages/ghost-documents.tsx
> +              <Td>{parent.title}</Td>
Oui, très juste. Merci

2022-01-18 11:48 UTC, m-maillot approved these changes
Nickel :+1:

2022-01-19 02:41 UTC, carolineBda approved these changes

2022-01-19 09:12 UTC, merged