fix(secu): add frontend http headers
SocialGouv/cdtn-admin pull request #793
Opened 2022-08-03 09:49 UTC by revolunet

fix #791

2022-08-25 07:45 UTC, ViCode approved these changes

2022-08-29 09:45 UTC, m-maillot requested changes
Sur le frotnend, on le gère directement dans le code via https://nextjs.org/docs/advanced-features/security-headers

Je pense que l'approche par le code plutôt que l'infra est plus adapté pour le profil de l'équipe et l'homogénéité dans nos projets. Qu'en pensez vous ? @ViCode @maxgfr 
C'est assez simple à faire en plus.

2022-08-29 12:46 UTC, maxgfr reviewed
Oui c'est vrai qu'avec le frontend, on le gère via `next.js`. Après, en effet, ça pourrait marcher ainsi (pour la statique oui, après si le seveur est de l'express, je pense qu'il faudrait comme sur le frontend)

2022-08-29 15:47 UTC, m-maillot commented
Version via next.js : https://github.com/SocialGouv/cdtn-admin/pull/802

2022-08-31 15:05 UTC, closed without merging